DATASET:
  DATA_TRAIN: ['ASDIV2K']
  DATA_VAL: ['ASDIV2K']
  DATA_EXT: 'sep'
  DATA_SCALE: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0]
  OUT_PATCH_SIZE: 192
LOG:
  SAVE: RCAN_x4
SOLVER:
  TEST_EVERY: 20
