SYSTEM:
  NUM_GPU: 2
  NUM_CPU: 8
MODEL:
  N_RESBLOCKS: 32
  N_RESGROUPS: 1
  BLOCK_TYPE: edsr_block
  PLANES: 256
  ACT_MODE: relu
  SHORT_SKIP: False
SOLVER:
  NAME: Lamb
  BASE_LR: 0.0032
  SAMPLES_PER_BATCH: 64
  ITERATION_TOTAL: 80000
